steps:
- task: NodeTool@0
  inputs:
    versionSpec: "10.15.1"
- task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
  inputs:
    keyfile: '.yarnrc, remote/.yarnrc, **/yarn.lock, !**/node_modules/**/yarn.lock, !**/.*/**/yarn.lock'
    targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
    vstsFeed: '$(ArtifactFeed)'
- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  inputs:
    versionSpec: "1.10.1"
- script: |
    yarn --frozen-lockfile
  displayName: Install Dependencies
  condition: and(succeeded(), ne(variables['CacheRestored'], 'true'))
- task: 1ESLighthouseEng.PipelineArtifactCaching.SaveCacheV1.SaveCache@1
  inputs:
    keyfile: '.yarnrc, remote/.yarnrc, **/yarn.lock, !**/node_modules/**/yarn.lock, !**/.*/**/yarn.lock'
    targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
    vstsFeed: '$(ArtifactFeed)'
  condition: and(succeeded(), ne(variables['CacheRestored'], 'true'))
- script: |
    yarn gulp electron-x64
  displayName: Download Electron
- script: |
    yarn gulp hygiene
  displayName: Run Hygiene Checks
- script: |
    yarn monaco-compile-check
  displayName: Run Monaco Editor Checks
- script: |
    yarn compile
  displayName: Compile Sources
- script: |
    yarn download-builtin-extensions
  displayName: Download Built-in Extensions
- script: |
    ./scripts/test.sh --tfs "Unit Tests"
  displayName: Run Unit Tests
- script: |
    ./scripts/test-integration.sh --tfs "Integration Tests"
  displayName: Run Integration Tests
- task: PublishTestResults@2
  displayName: Publish Tests Results
  inputs:
    testResultsFiles: '*-results.xml'
    searchFolder: '$(Build.ArtifactStagingDirectory)/test-results'
  condition: succeededOrFailed()